name: MKS Gold Price Scheduler

# BLOK PERMISSION YANG TELAH DITAMBAH (PENTING)
permissions:
  contents: write 

# BLOK JADUAL (Telah diselaraskan jarak tepinya)
on:
  # Tetapkan untuk berjalan setiap 5 minit
  schedule:
    - cron: '*/5 * * * *'
  
  # Benarkan trigger manual
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run MKS Scraper
        run: node mks.js
        
      # Commit dan push fail mks.json yang telah dikemaskini
      - name: Commit and Push mks.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update MKS Gold Prices
          files: mks.json
