name: MKS Gold Price Scheduler

# Kebenaran ini membenarkan Action untuk 'WRITE' (menulis/mengubah) fail ke repository.
permissions:
  contents: write 

# Bila Action ini akan berjalan
on:
  # Tetapkan untuk berjalan setiap 5 minit (Pastikan indentation betul)
  schedule:
    - cron: '*/5 * * * *'
  
  # Benarkan trigger manual
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run MKS Scraper
        run: node mks.js
        
      # Commit dan push fail mks.json yang telah dikemaskini
      - name: Commit and Push mks.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update MKS Gold Prices
          # PENTING: Fail yang perlu di-commit
          files: mks.json
          # PENTING: Commit ke branch sedia ada
          create_branch: false
